function [T] = HTM(t,alpha,a,d)
    T = [cosd(t),-1*sind(t)*cosd(alpha),sind(t)*sind(alpha),a*cosd(t);...
        sind(t),cosd(t)*cosd(alpha),-1*cosd(t)*sind(alpha),a*sind(t);...
        0,sind(alpha),cosd(alpha),d;...
        0,0,0,1];
end