function [y1,y2] = SBXCrossover(x1,x2)

    % sbx crossover
  
    n = numel(x1);
    c = zeros(n, 2);
    for i = 1:n
              
        %% find eta
        eta = 20;

        %% find mu
        mu = unifrnd(0,1);

        %% find beta: a random value that needs to be regenerated for each dimension
        if mu <= 0.5
            beta = (2*mu)^(1/(eta+1));
        else
            beta = (2*(1-mu))^(-1/(eta+1));
        end

        %% 2 children generated by SBX cross-over operator
        c(i,1) = ((1+beta)*x1(i) + (1-beta)*x2(i))/2;
        c(i,2) = ((1-beta)*x1(i) + (1+beta)*x2(i))/2;
      
    end
  
    y1 = c(:,1)';
    y2 = c(:,2)';
    %z = [y1,y2]';
end

